---
title: "summer mean CH-Lae"
output: html_document
date: "2022-09-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readr)
library(visdat)
library(ggplot2)
library(ggrepel)
```


```{r cars}
## 2004-2020
df <- read_csv("~/data/icos_releaseX/MM/FLX_CH-Lae_FLUXNET2015_FULLSET_MM_2004-2020_beta-3.csv") %>% 
  select(TIMESTAMP,
         starts_with("VPD"),
         starts_with("TA_F_MDS")
         ) %>%
  mutate(date = lubridate::ym(TIMESTAMP)) %>%
  na_if(-9999) %>% 
  select(TIMESTAMP, date, vpd = VPD_F_MDS, temp = TA_F_MDS)
```

```{r}
df %>% 
  vis_miss()
```

```{r}
df %>% 
  ggplot(aes(date, temp)) +
  geom_line()

df %>% 
  ggplot(aes(date, vpd)) +
  geom_line()
```

```{r}
df_agg <- df %>% 
  mutate(year = lubridate::year(date)) %>% 
  mutate(month = lubridate::month(date)) %>% 
  filter(month %in% c(6,7,8)) %>% 
  group_by(year) %>% 
  summarise(vpd = mean(vpd), temp = mean(temp))

df_agg %>% 
  mutate(highlight = ifelse(year %in% c(2015, 2018, 2019), TRUE, FALSE)) %>% 
  ggplot(aes(temp, vpd, label = year)) +
  geom_text_repel(aes(temp, vpd, label = year), color = "grey30") +
  geom_point(aes(color = highlight) , size = 2) +
  scale_color_manual(values = c("black", "red")) +
  theme_classic() + 
  theme(legend.position = "none") +
  labs(x = expression(paste("Temperature (ºC)")), y = "VPD (hPa)")

ggsave("~/cagibi/fig/temp_vpd_ch-lae.pdf", width = 4, height = 3.5)
ggsave("~/cagibi/fig/temp_vpd_ch-lae.png", width = 4, height = 3.5)
```
